/**
 * Jenkinsfile
 *
 * Jenkins Pipeline to provision bare metal slaves in beaker.
 */
properties([
  parameters([
    choiceParam(
      name: 'ARCH',
      choices: "x86_64\nppc64le\naarch64\ns390x",
      description: 'Architecture'
    )
  ])
])

node ('jenkins-slave') {
    ansiColor('xterm') {
        timestamps {
            def jslaveName = 'jenkins-slave-' + env.BUILD_NUMBER + '-' + params.ARCH
            env.JSLAVE_NAME = jslaveName
            env.JSLAVE_LABEL = jslaveName
            env.ARCH = params.ARCH
          
            stage('Setup') {
                // TODO - set cinchpin configuration from parameters
                 dir('ci-pipeline') {
                    git 'https://github.com/jaypoulz/multiarch-ci-pipeline'
                    sh 'kinit -k jpoulin@REDHAT.COM'
                }
            }
            
            stage('Provision') {
                dir('ci-pipeline') {
                  def slaveTarget = "jenkins-slave-${params.ARCH}"
                  sh "linchpin up ${slaveTarget}"
                  sh "cinch inventories/${slaveTarget}.inventory"
                }
            }

            stage('Archive') {
                dir('ci-pipeline') {
                    archiveArtifacts artifacts: 'inventories/cinch.inventory', fingerprint: true
                    archiveArtifacts artifacts: 'resources/cinch.output', fingerprint: true

                    // Archive slave name in a slave.properties file
                    writeFile(file: 'slave.properties', text: "name:${jslaveName}")
                    archiveArtifacts artifacts: 'slave.properties', fingerprint: true
                }
            }
        }
    }
}
