---
- hosts: jenkins_slave
  tasks:
    - lineinfile:
        file: /etc/containers/registries.conf
        line: 'insecure_registries:'

    - lineinfile:
        file: /etc/containers/registries.conf
        line: '  - 172.30.0.0/16'


    - name: install dependencies
      yum: pkg={{item}} state=installed
      with_items:
      - bc
      - git
      - make
      - golang
      - docker
      - jq
      - bind-utils

    - service: name=docker state=started
