ansible_user: root
ansible_private_key_file: ~/.ssh/id_rsa
ansible_connection: ssh
certificate_authority_urls:
  - https://password.corp.redhat.com/legacy.crt
  - https://password.corp.redhat.com/RH-IT-Root-CA.crt
  - https://engineering.redhat.com/Eng-CA.crt
rhel_base_urls:
  x86_64: "http://pulp.dist.prod.ext.phx2.redhat.com/content/dist/rhel/server/7/7Server/"
  ppc64le: "http://pulp.dist.prod.ext.phx2.redhat.com/content/dist/rhel/power-le/7/7Server"
  s390x: "http://pulp.dist.prod.ext.phx2.redhat.com/content/dist/rhel/system-z/7/7Server/"
  aarch: "http://pulp.dist.prod.ext.phx2.redhat.com/content/dist/rhel/arm-64/7/7Server/"
rhel_base: "{{ rhel_base_urls[lookup('env', 'ARCH')] }}"


# URL to Jenkins master for the slave to connect to
jenkins_master_url: 'https://multiarch-qe-aos-jenkins.rhev-ci-vms.eng.rdu2.redhat.com'
jslave_name: "{{ lookup('env', 'JSLAVE_NAME') }}"
jslave_label: "{{ lookup('env', 'JSLAVE_LABEL') }}"

# Jenkins Slave Registration Credentials
jenkins_slave_username: "{{ lookup('env', 'JENKINS_SLAVE_USERNAME') }}"
jenkins_slave_password: "{{ lookup('env', 'JENKINS_SLAVE_PASSWORD') }}"
