ansible_user: root
ansible_private_key_file: "~/.ssh/id_rsa"
ansible_connection: ssh
certificate_authority_urls:   
  - https://password.corp.redhat.com/legacy.crt
  - https://password.corp.redhat.com/RH-IT-Root-CA.crt
  - https://engineering.redhat.com/Eng-CA.crt
rhel_base: http://pulp.dist.prod.ext.phx2.redhat.com/content/dist/rhel/power-le/7/7Server

# URL to Jenkins master for the slave to connect to
jenkins_master_url: 'https://multiarch-qe-aos-jenkins.rhev-ci-vms.eng.rdu2.redhat.com'
jslave_name: "{{ lookup('env', 'JSLAVE_NAME') }}"
jslave_label: "{{ lookup('env', 'JSLAVE_LABEL') }}"

# Jenkins Slave Registration Credentials
jenkins_slave_username: "{{ lookup('env', 'JENKINS_SLAVE_USERNAME') }}"
jenkins_slave_password: "{{ lookup('env', 'JENKINS_SLAVE_PASSWORD') }}"
