jenkins_master_url: 'multiarch-qe-aos-jenkins.rhev-ci-vms.eng.rdu2.rehdat.com' # URL to Jenkins master for the slave to connect to
jslave_name: 'cinch-slave'
jslave_label: 'cinch-slave'
# If your Jenkins master requires authentication to connect a slave,
# add credentials via the two variables below.  If anonymous users can
# connect slaves to the master, do not include the following two
# variables in this layout file.
#jenkins_slave_username: 'automation-user'
#jenkins_slave_password: 'jenkinsAPItoken'
#
