---
- name: deploy openshift cluster
  hosts: openshift_master
  vars_prompt:
    - name: kerberos_principal
      private: no
      prompt: |
        Call ansible-playbook with '-e "kerberos_principal=<your kerberos username>"'
        to skip this prompt. Please enter your kerberos principal.
  tasks:
    - name: check ansible version is 2.5 or higher
      local_action:
        module: fail
        msg: requires ansible version 2.5 or higher
      when: ansible_version.full is version('2.5', '<=')
    - name: deploy openshift cluster
      include_tasks: ./playbooks/deploy_cluster.yml
      when: deploy_cluster
    - name: set up multiarch ci provisioner
      include_tasks: ./playbooks/setup_provisioner.yml
      when: deploy_provisioner
