---
- name: upgrade openshift cluster
  hosts: openshift_master
  tasks:
    - name: check ansible version is 2.5 or higher
      local_action:
        module: fail
        msg: requires ansible version 2.5 or higher
      when: ansible_version.full is version('2.5', '<=')
    - name: upgrade openshift cluster
      include_tasks: ./playbooks/upgrade_provisioner.yml
